// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Mohashan.UserManager.Persistence;

#nullable disable

namespace Mohashan.UserManager.Persistence.Migrations
{
    [DbContext(typeof(UserManagerDbContext))]
    [Migration("20230805185326_initialMigration")]
    partial class initialMigration
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Mohashan.UserManager.Domain.Entities.Feature", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedDateTime")
                        .HasColumnType("datetime2");

                    b.Property<string>("DataType")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DeletedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("DeletedDateTime")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<string>("LastModifiedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("LastModifiedDateTime")
                        .HasColumnType("datetime2");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id");

                    b.ToTable("Features");

                    b.HasData(
                        new
                        {
                            Id = new Guid("d72c5f77-667d-4a73-a426-1f76e18a93b5"),
                            CreatedBy = "Seeder",
                            CreatedDateTime = new DateTime(2023, 8, 5, 22, 23, 26, 73, DateTimeKind.Local).AddTicks(7453),
                            DataType = "String",
                            DeletedDateTime = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsDeleted = false,
                            LastModifiedDateTime = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "MobileNumber"
                        },
                        new
                        {
                            Id = new Guid("b8d7034b-176f-46ca-8a77-ddbf8d5518cc"),
                            CreatedBy = "Seeder",
                            CreatedDateTime = new DateTime(2023, 8, 5, 22, 23, 26, 73, DateTimeKind.Local).AddTicks(7484),
                            DataType = "String",
                            DeletedDateTime = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsDeleted = false,
                            LastModifiedDateTime = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Email"
                        });
                });

            modelBuilder.Entity("Mohashan.UserManager.Domain.Entities.Group", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedDateTime")
                        .HasColumnType("datetime2");

                    b.Property<string>("DeletedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("DeletedDateTime")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<string>("LastModifiedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("LastModifiedDateTime")
                        .HasColumnType("datetime2");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id");

                    b.ToTable("Groups");

                    b.HasData(
                        new
                        {
                            Id = new Guid("0446761a-0d10-4a85-afb6-c0c0a1ed4fbd"),
                            CreatedBy = "Seeder",
                            CreatedDateTime = new DateTime(2023, 8, 5, 22, 23, 26, 73, DateTimeKind.Local).AddTicks(7561),
                            DeletedDateTime = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsDeleted = false,
                            LastModifiedDateTime = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "AdminGroup"
                        },
                        new
                        {
                            Id = new Guid("6f74e22b-04a3-4eda-b7b0-b9e1fe8b963d"),
                            CreatedBy = "Seeder",
                            CreatedDateTime = new DateTime(2023, 8, 5, 22, 23, 26, 73, DateTimeKind.Local).AddTicks(7568),
                            DeletedDateTime = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsDeleted = false,
                            LastModifiedDateTime = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "ReportGroup"
                        });
                });

            modelBuilder.Entity("Mohashan.UserManager.Domain.Entities.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedDateTime")
                        .HasColumnType("datetime2");

                    b.Property<string>("DeletedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("DeletedDateTime")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<string>("LastModifiedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("LastModifiedDateTime")
                        .HasColumnType("datetime2");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<Guid>("UserTypeId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("UserTypeId");

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            Id = new Guid("34d442ac-d567-4603-9ff8-f78727330629"),
                            CreatedBy = "Seeder",
                            CreatedDateTime = new DateTime(2023, 8, 5, 22, 23, 26, 73, DateTimeKind.Local).AddTicks(7549),
                            DeletedDateTime = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsDeleted = false,
                            LastModifiedDateTime = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Admin",
                            UserTypeId = new Guid("743478cc-0688-4fb0-abae-e920cd7a52bd")
                        });
                });

            modelBuilder.Entity("Mohashan.UserManager.Domain.Entities.UserFeature", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedDateTime")
                        .HasColumnType("datetime2");

                    b.Property<string>("DeletedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("DeletedDateTime")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("FeatureId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<string>("LastModifiedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("LastModifiedDateTime")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Value")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.HasIndex("FeatureId");

                    b.HasIndex("UserId");

                    b.ToTable("userFeatures");

                    b.HasData(
                        new
                        {
                            Id = new Guid("3cb6e6de-914f-4fae-83c1-e6dc65c23eb3"),
                            CreatedBy = "Seeder",
                            CreatedDateTime = new DateTime(2023, 8, 5, 22, 23, 26, 73, DateTimeKind.Local).AddTicks(7589),
                            DeletedDateTime = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FeatureId = new Guid("d72c5f77-667d-4a73-a426-1f76e18a93b5"),
                            IsDeleted = false,
                            LastModifiedDateTime = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            UserId = new Guid("34d442ac-d567-4603-9ff8-f78727330629"),
                            Value = "09011500119"
                        },
                        new
                        {
                            Id = new Guid("2969947c-a78d-44eb-9c11-0091d5711ef5"),
                            CreatedBy = "Seeder",
                            CreatedDateTime = new DateTime(2023, 8, 5, 22, 23, 26, 73, DateTimeKind.Local).AddTicks(7597),
                            DeletedDateTime = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FeatureId = new Guid("b8d7034b-176f-46ca-8a77-ddbf8d5518cc"),
                            IsDeleted = false,
                            LastModifiedDateTime = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            UserId = new Guid("34d442ac-d567-4603-9ff8-f78727330629"),
                            Value = "msh200x@gmail.com"
                        });
                });

            modelBuilder.Entity("Mohashan.UserManager.Domain.Entities.UserGroup", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedDateTime")
                        .HasColumnType("datetime2");

                    b.Property<string>("DeletedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("DeletedDateTime")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("GroupId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<string>("LastModifiedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("LastModifiedDateTime")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("GroupId");

                    b.HasIndex("UserId");

                    b.ToTable("userGroups");

                    b.HasData(
                        new
                        {
                            Id = new Guid("74efd38f-70c1-4261-aed8-3932800c0df3"),
                            CreatedBy = "Seeder",
                            CreatedDateTime = new DateTime(2023, 8, 5, 22, 23, 26, 73, DateTimeKind.Local).AddTicks(7575),
                            DeletedDateTime = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            GroupId = new Guid("0446761a-0d10-4a85-afb6-c0c0a1ed4fbd"),
                            IsDeleted = false,
                            LastModifiedDateTime = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            UserId = new Guid("34d442ac-d567-4603-9ff8-f78727330629")
                        },
                        new
                        {
                            Id = new Guid("6121ab3e-fc99-4cc2-8874-221fea3e77f3"),
                            CreatedBy = "Seeder",
                            CreatedDateTime = new DateTime(2023, 8, 5, 22, 23, 26, 73, DateTimeKind.Local).AddTicks(7582),
                            DeletedDateTime = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            GroupId = new Guid("6f74e22b-04a3-4eda-b7b0-b9e1fe8b963d"),
                            IsDeleted = false,
                            LastModifiedDateTime = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            UserId = new Guid("34d442ac-d567-4603-9ff8-f78727330629")
                        });
                });

            modelBuilder.Entity("Mohashan.UserManager.Domain.Entities.UserType", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedDateTime")
                        .HasColumnType("datetime2");

                    b.Property<string>("DeletedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("DeletedDateTime")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<string>("LastModifiedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("LastModifiedDateTime")
                        .HasColumnType("datetime2");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id");

                    b.ToTable("UserTypes");

                    b.HasData(
                        new
                        {
                            Id = new Guid("743478cc-0688-4fb0-abae-e920cd7a52bd"),
                            CreatedBy = "Seeder",
                            CreatedDateTime = new DateTime(2023, 8, 5, 22, 23, 26, 73, DateTimeKind.Local).AddTicks(7494),
                            DeletedDateTime = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsDeleted = false,
                            LastModifiedDateTime = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Human"
                        },
                        new
                        {
                            Id = new Guid("6ab3ffdf-8381-45b7-aa87-08829ba2e38e"),
                            CreatedBy = "Seeder",
                            CreatedDateTime = new DateTime(2023, 8, 5, 22, 23, 26, 73, DateTimeKind.Local).AddTicks(7538),
                            DeletedDateTime = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsDeleted = false,
                            LastModifiedDateTime = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "System"
                        });
                });

            modelBuilder.Entity("Mohashan.UserManager.Domain.Entities.User", b =>
                {
                    b.HasOne("Mohashan.UserManager.Domain.Entities.UserType", "UserType")
                        .WithMany()
                        .HasForeignKey("UserTypeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("UserType");
                });

            modelBuilder.Entity("Mohashan.UserManager.Domain.Entities.UserFeature", b =>
                {
                    b.HasOne("Mohashan.UserManager.Domain.Entities.Feature", "Feature")
                        .WithMany("UserFeatures")
                        .HasForeignKey("FeatureId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Mohashan.UserManager.Domain.Entities.User", "User")
                        .WithMany("UserFeatures")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Feature");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Mohashan.UserManager.Domain.Entities.UserGroup", b =>
                {
                    b.HasOne("Mohashan.UserManager.Domain.Entities.Group", "Group")
                        .WithMany("UserGroups")
                        .HasForeignKey("GroupId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Mohashan.UserManager.Domain.Entities.User", "User")
                        .WithMany("UserGroup")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Group");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Mohashan.UserManager.Domain.Entities.Feature", b =>
                {
                    b.Navigation("UserFeatures");
                });

            modelBuilder.Entity("Mohashan.UserManager.Domain.Entities.Group", b =>
                {
                    b.Navigation("UserGroups");
                });

            modelBuilder.Entity("Mohashan.UserManager.Domain.Entities.User", b =>
                {
                    b.Navigation("UserFeatures");

                    b.Navigation("UserGroup");
                });
#pragma warning restore 612, 618
        }
    }
}
